#!/bin/bash


# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)" >> /Users/ncko/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

xcode-select --install
brew install python3

export PATH="$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:$PATH"

sudo -H pip3 install --upgrade pip && pip3 install ansible

# clone ansible repo
mkdir -p ~/projects/$USER
cd ~/projects/$USER
git clone https://github.com/ncko/mac-dev-playbook
cd mac-dev-playbook

## install ansible roles
ansible-galaxy install -r requirements.yml

## run ansible playbook
# ansible-playbook main.yml --ask-become-pass
